server:
  port: 8888

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/membership?characterEncoding=utf8&connectTimeout=1000&socketTimeout=3000&autoReconnect=true&useUnicode=true&useSSL=false&serverTimezone=UTC
    username: root
    password: lfpxtt12
    driver-class-name: com.mysql.cj.jdbc.Driver



mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml

#showSql
logging:
  level:
    com:
      sap:
        membership:
          mapper: info

dubbo:
    application.name: dubbo-spring-boot-starter-membership-provider
    application:
      registries:
        server: true
    scan:
      base-packages: com.sap.membership
    protocol:
      name: dubbo
      port: 12345
    registry:
      address: 127.0.0.1
      port: 2181