server:
  port: 8888

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/membership
    username: root
    password: lfpxtt12
    driver-class-name: com.mysql.cj.jdbc.Driver



mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml

#showSql
logging:
  level:
    com:
      sap:
        membership:
          mapper: info

  spring:
    application.name: dubbo-spring-boot-starter
    dubbo.server: true
    dubbo.registry: N/A